1619622432396 [Opening serial port: /dev/ttyTHS1.] 
1619622432697 [The robot is connected to ] [/dev/ttyTHS1] 
1619622432698 [Initial robot's topic...] 
1619622439183 [Data from: [w]] 
1619622439184 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622439338 [Data from: [ ]] 
1619622439338 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 62, in write_command
    for i in len(command_send):
TypeError: 'int' object is not iterable
] 
1619622439353 [Data from: [w]] 
1619622439353 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622439850 [Data from: [w]] 
1619622439850 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622439880 [Data from: [w]] 
1619622439880 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622439911 [Data from: [w]] 
1619622439911 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622439942 [Data from: [w]] 
1619622439942 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622439974 [Data from: [w]] 
1619622439974 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622440001 [Data from: [ ]] 
1619622440001 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 62, in write_command
    for i in len(command_send):
TypeError: 'int' object is not iterable
] 
1619622440014 [Data from: [w]] 
1619622440014 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622440370 [Data from: [ ]] 
1619622440370 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 62, in write_command
    for i in len(command_send):
TypeError: 'int' object is not iterable
] 
1619622441433 [Data from: [w]] 
1619622441434 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622441934 [Data from: [w]] 
1619622441934 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622441964 [Data from: [w]] 
1619622441964 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622441996 [Data from: [w]] 
1619622441996 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442029 [Data from: [w]] 
1619622442030 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442061 [Data from: [w]] 
1619622442061 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442092 [Data from: [w]] 
1619622442092 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442131 [Data from: [w]] 
1619622442132 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442177 [Data from: [w]] 
1619622442177 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442217 [Data from: [w]] 
1619622442217 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442250 [Data from: [w]] 
1619622442250 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442287 [Data from: [w]] 
1619622442287 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442317 [Data from: [w]] 
1619622442317 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442348 [Data from: [w]] 
1619622442348 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 98, in handle_command
    self.set_speed([self._current_speed, self._current_speed])
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 300, in set_speed
    self.__robot_serial.set_speed(speed_data)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 96, in set_speed
    command += speed.to_bytes(2, 'little')
AttributeError: 'int' object has no attribute 'to_bytes'
] 
1619622442382 [Data from: [ ]] 
1619622442383 [handle_key_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Robot.py", line 92, in handle_command
    self.release_motor()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_control.py", line 206, in release_motor
    self.__robot_serial.set_stop()
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 102, in set_stop
    self.write_command(command)
  File "/home/khoixx/dev_ros1_ws/src/execute/src/robot_command.py", line 62, in write_command
    for i in len(command_send):
TypeError: 'int' object is not iterable
] 
