1617988038452 [handle_command@Exception] [Traceback (most recent call last):
  File "/home/khoixx/dev_ros1_ws/src/execute/src/Arm_moveit.py", line 94, in handle_command
    self.group.set_position_target([self.target.position.x,self.target.position.y,self.target.position.z])
AttributeError: moveit_handle instance has no attribute 'target'
] 
1617988038469 [Finish initializing arm_moveit] 
1617988038810 [Position received] 
1617988039811 [command: %f] [2] 
